/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/_search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchIndexRouteImport } from './routes/_search.index'
import { Route as SearchMessagesMessageIdRouteImport } from './routes/_search.messages.$messageId'

const SearchRoute = SearchRouteImport.update({
  id: '/_search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SearchRoute,
} as any)
const SearchMessagesMessageIdRoute = SearchMessagesMessageIdRouteImport.update({
  id: '/messages/$messageId',
  path: '/messages/$messageId',
  getParentRoute: () => SearchRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SearchIndexRoute
  '/settings': typeof SettingsRoute
  '/messages/$messageId': typeof SearchMessagesMessageIdRoute
}
export interface FileRoutesByTo {
  '/settings': typeof SettingsRoute
  '/': typeof SearchIndexRoute
  '/messages/$messageId': typeof SearchMessagesMessageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_search': typeof SearchRouteWithChildren
  '/settings': typeof SettingsRoute
  '/_search/': typeof SearchIndexRoute
  '/_search/messages/$messageId': typeof SearchMessagesMessageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/settings' | '/messages/$messageId'
  fileRoutesByTo: FileRoutesByTo
  to: '/settings' | '/' | '/messages/$messageId'
  id:
    | '__root__'
    | '/_search'
    | '/settings'
    | '/_search/'
    | '/_search/messages/$messageId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SearchRoute: typeof SearchRouteWithChildren
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_search': {
      id: '/_search'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_search/': {
      id: '/_search/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof SearchRoute
    }
    '/_search/messages/$messageId': {
      id: '/_search/messages/$messageId'
      path: '/messages/$messageId'
      fullPath: '/messages/$messageId'
      preLoaderRoute: typeof SearchMessagesMessageIdRouteImport
      parentRoute: typeof SearchRoute
    }
  }
}

interface SearchRouteChildren {
  SearchIndexRoute: typeof SearchIndexRoute
  SearchMessagesMessageIdRoute: typeof SearchMessagesMessageIdRoute
}

const SearchRouteChildren: SearchRouteChildren = {
  SearchIndexRoute: SearchIndexRoute,
  SearchMessagesMessageIdRoute: SearchMessagesMessageIdRoute,
}

const SearchRouteWithChildren =
  SearchRoute._addFileChildren(SearchRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SearchRoute: SearchRouteWithChildren,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
